---

- hosts: all
  become: true
  gather_facts: no
  roles:
   - { role: docker_role }

- hosts: gitlab
  become: true
  gather_facts: no
  roles:
    - { role: gitlab_role }
    - { role: gitlab_monitoring_role }
- hosts: letsencrypt
  become: true
  gather_facts: no
  roles:
    - { role: letsencrypt_role }

- hosts: jenkins
  become: true
  gather_facts: no
  roles:
    - { role: jenkins_role }

...
