---

- hosts: gitlab
  become: true
  gather_facts: no
  roles:
    - { role: gitlab-role }

#- hosts: letsencrypt
#  become: true
#  gather_facts: no
#  roles:
#    - { role: letsencrypt-role }

...
