---
# tasks file for jenkins_k8s_role
- name: Add the Cloud SDK distribution URI as a package source
  shell: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

- name: Update system
  apt: update_cache=yes

- name: Install pip
  apt:
    name: python-pip

- name: Apt-transport-https install
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - gnupg

- name: Install tar
  apt:
    name: tar

- name: Import the Google Cloud public key
  shell: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

- name: Update system
  apt: update_cache=yes

- name: Install gcloud sdk
  apt: 
    name: google-cloud-sdk

- name: Install kubectl
  apt: 
    name: kubectl

- name: Copy service-account credentials file
  copy:
    src: key.json
    dest: /key.json

- name: Copy linter for Java code
  copy:
    src: checkstyle-8.30-all.jar
    dest: /checkstyle-8.30-all.jar

- name: Unzip go.tar
  unarchive: 
    src: https://dl.google.com/go/go1.11.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: Install flake8
  pip: 
    name: flake8 

- name: Enable the NodeSource repository
  shell: curl -sL https://deb.nodesource.com/setup_10.x | bash

- name: Install Node.js
  apt:
    name: nodejs

- name: Install linter for node.js
  shell: npm i -g eslint    
...
