---
# tasks file for gitlab-monitoring_role
############ Install stackdriver-agent ################

- name: Copy monitoring-agent script
  copy:
    src: install-monitoring-agent.sh
    dest: /home/{{ ansible_user }}/

- name: Run script
  shell:
    cmd: bash install-monitoring-agent.sh
    chdir: /home/{{ ansible_user }}/

############ Monitoring setup for Nginx ###############

- name: Enable the Nginx monitoring plugin
  copy:
    src: nginx.conf
    dest: /opt/stackdriver/collectd/etc/collectd.d/

############ Monitoring setup for Redis ###############
- name: Install hiredis client library
  apt:
    name: libhiredis0.13

- name: Copy the Redis configuration file
  copy:
    src: redis.conf
    dest: /opt/stackdriver/collectd/etc/collectd.d/
############ Add credentials ##########################

- name: Create credential destonation folder
  file:
    path: /etc/google/auth
    state: directory
    

- name: Add credential
  copy:
    src: application_default_credentials.json
    dest: /etc/google/auth
    owner: root
    group: root
    mode: '0400'

############ Restart the monitoring agent #############
- name: Restart the monitoring agent
  service:
    name: stackdriver-agent
    state: restarted
...
