---
# tasks file for jenkins-role
- name: Upgrade system
  apt: upgrade=dist update_cache=yes

- name: Install jdk
  apt: name=openjdk-8-jdk state=latest

- name: Install jre
  apt: name=openjdk-8-jre state=latest

- name: Add jenkins key
  shell: wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -

- name: Add jenkins list
  shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: Upgrade system
  apt: upgrade=dist update_cache=yes

- name: Install jenkins
  apt: 
    name: jenkins=2.204.2

# restore part

- name: "Install boto python package"
  apt: name=python-boto state=latest

- name: "Create backup directory"
  file: path=/tmp/backup state=directory

- name: "Upload restore script"
  copy: src=jenkins-restore.sh dest=/tmp/backup/jenkins-restore.sh mode=0755

- name: "Download backup file from gcloud"
  gc_storage:
    bucket: '{{ gcloud_storage_name }}'
    object: '{{ gcloud_tar_name }}'
    dest: /tmp/backup/{{ gcloud_tar_name }}
    gs_access_key: '{{ gcloud_storage_key }}'
    gs_secret_key: '{{ gcloud_storage_secret_key }}'
    mode: get

-  name: "Restore jenkins home directory"
   shell: /tmp/backup/jenkins-restore.sh /var/lib/jenkins /tmp/backup/{{ gcloud_tar_name }}

- name: "Restore ownership"
  shell: chown jenkins.jenkins -R /var/lib/jenkins

- name: "Remove backup file"
  file: path=/tmp/backup/{{ gcloud_tar_name }} state=absent

- name: "Restart jenkins"
  service: name=jenkins state=restarted
